# Generated by Django 3.2 on 2022-06-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paperlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('pags', models.TextField(verbose_name='内容')),
                ('ifok', models.BooleanField(default=False, verbose_name='是否显示')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公告列表',
                'verbose_name_plural': '公告列表',
            },
        ),
        migrations.CreateModel(
            name='playerlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('player', models.CharField(max_length=9999, verbose_name='玩家名')),
                ('mail', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('ifok', models.NullBooleanField(default=None, verbose_name='处理结果')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '申请列表',
                'verbose_name_plural': '申请列表',
            },
        ),
    ]
