# Generated by Django 3.2 on 2022-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_paperlist_ifok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperlist',
            name='ifok',
            field=models.BooleanField(default=False, verbose_name='是否显示'),
        ),
    ]
